services:
  - type: web
    name: my-first-repo
    env: node
    plan: free
    rootDir: package.json
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: IP_SALT
        generateValue: true
